home:
  path:   /
  controller: App\Controller\GestorController::index        

crearCliente:
  path:   /crear-cliente
  controller: App\Controller\GestorController::createCliente

enviarCliente:
  path:   /enviar-cliente
  controller: App\Controller\GestorController::sendCliente  

crearFactura:
  path: /crear-factura
  controller: App\Controller\GestorController::crearFactura  

generarFactura:
  path: /generar-factura
  controller: App\Controller\GestorController::generarFactura  